name: Run volume limited arbitrage pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main and develop branches.
on: workflow_dispatch

env:
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: End-to-end tests
        run: |
          python3 -m test.ci
